### ISSUE TITLE
Plain run of swift_scrapper.py do not generate swift codes dataset

### ISSUE THREAD

**Issue by danielcollsol** [danielcollsol/web_scraping#2]
Hi Guillermo,

I tried running swift_scrapper.py to generate the scraped dataset but couldn't. 

Firstly, I encountered the error: "main() missing 1 required positional arguments: 'output_path'". As a workaround, I modified the main function default parameters to load the dataset into the data>final folder. I guess it is programmed to retrieve that output folder in another way (perhaps as an environment variable) but I couldn't find it.

Then, the scrapping worked (or at least the data points were printed) but it did not load the output dataset in the final folder. For this, I guess the workaround I did previously disrupted the workflow.

Probably I am missing something and I have thought that less experienced programmers might miss it too.

Can you think of a way of updating the code so the swift data can be directly scrapped? What do you think?

Cheers,
Dani

**Comment by geblanco** [comment]
Hi @danielcollsol ,

Could elaborate more on the error? How did you launch the program? With what arguments? Can you add the full stacktrace?

Also, there are no instructions in the README as to how to use this script, perhaps that would be the starting point for anyone wanting to use it?

Best,
Guillermo.

**Comment by geblanco** [comment]
Hi @danielcollsol,

Friendly ping :)

**Comment by danielcollsol** [comment]
Hi Guillermo,

Sorry for not answering ealier, this last week has been crazy. We are all
meeting this week in Pisa and have been preparing the trip.

I keep in mind that I owe you an more detailed description of the issue I
encountered. I will try to answer you asap. Probably tomorrow. :)

Best,
Dani

**Comment by danielcollsol** [comment]
Hi @geblanco,

I could explain to you how I did try to add the arguments and execute the code but I am sure it is not the way to do it.

Could you add a section in the readme file describing how to do so? So I could follow the instructions and check if I can make it run.

**Comment by geblanco** [comment]
Hi @danielcollsol,

Is this still an issue? Or we can close this now?

**Comment by danielcollsol** [comment]
Hi Guillermo,

The code works like a charm so yes, we can close the issue.

Best,
Dani

**Comment by geblanco** [comment]
Perfect! Closing now :smile:
